// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNlRH9QNNuBtr3HaiH-EcWCXAtykcJKgM',
    appId: '1:100628826907:android:732bcb9d394155cd9d21be',
    messagingSenderId: '100628826907',
    projectId: 'vodovoz-1688a',
    storageBucket: 'vodovoz-1688a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_hmgzHkotSY_40WWoxz7sTbqSAP2DSmc',
    appId: '1:100628826907:ios:dcaa54f74a87ad6b9d21be',
    messagingSenderId: '100628826907',
    projectId: 'vodovoz-1688a',
    storageBucket: 'vodovoz-1688a.appspot.com',
    androidClientId:
        '100628826907-r50ngdcvmfmvdrijlve3lp6t49mchi3o.apps.googleusercontent.com',
    iosClientId:
        '100628826907-f31avqf5bl3je7tpj08lbh6qmvdfe9bk.apps.googleusercontent.com',
    iosBundleId: 'com.example.vodovoz',
  );
}
